//! PHMM initialization artifact contracts and manifest I/O.

use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};

use crate::error::{PreAdPrepError, Result};
use crate::export::{ArraySpec, DataType, write_npy_2d};

pub const TRANSITION_ORDER: [&str; 9] = [
    "_mm", "_md", "_mi", "_dm", "_dd", "_di", "_im", "_id", "_ii",
];

/// Initialization tracks generated by preprocessing.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum InitializationTrack {
    LegacyCurrent,
    ReferenceMsa,
}

impl InitializationTrack {
    pub fn as_manifest_str(self) -> &'static str {
        match self {
            Self::LegacyCurrent => "legacy_current",
            Self::ReferenceMsa => "reference_msa",
        }
    }

    pub fn from_manifest_str(value: &str) -> Result<Self> {
        match value {
            "legacy_current" => Ok(Self::LegacyCurrent),
            "reference_msa" => Ok(Self::ReferenceMsa),
            other => Err(PreAdPrepError::Validation(format!(
                "unknown initialization track: {other}"
            ))),
        }
    }
}

/// Common initialization manifest for all PHMM initialization tracks.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct InitialPhmmManifest {
    pub track: InitializationTrack,
    pub global_state_count: usize,
    pub alphabet_size: usize,
    pub transition_order: Vec<String>,
    pub match_emission: ArraySpec,
    pub insert_emission: ArraySpec,
    pub transition_logits: ArraySpec,
    pub metadata: Vec<(String, String)>,
}

impl InitialPhmmManifest {
    pub fn new(
        track: InitializationTrack,
        global_state_count: usize,
        alphabet_size: usize,
        match_emission: ArraySpec,
        insert_emission: ArraySpec,
        transition_logits: ArraySpec,
    ) -> Self {
        Self {
            track,
            global_state_count,
            alphabet_size,
            transition_order: TRANSITION_ORDER
                .iter()
                .map(|value| value.to_string())
                .collect(),
            match_emission,
            insert_emission,
            transition_logits,
            metadata: Vec::new(),
        }
    }

    pub fn with_metadata(mut self, key: impl Into<String>, value: impl Into<String>) -> Self {
        self.metadata.push((key.into(), value.into()));
        self
    }

    pub fn validate_shapes(&self) -> Result<()> {
        if self.match_emission.shape != vec![self.global_state_count, self.alphabet_size] {
            return Err(PreAdPrepError::Validation(format!(
                "match_emission shape {:?} does not match [{} , {}]",
                self.match_emission.shape, self.global_state_count, self.alphabet_size
            )));
        }
        if self.insert_emission.shape != vec![self.global_state_count + 1, self.alphabet_size] {
            return Err(PreAdPrepError::Validation(format!(
                "insert_emission shape {:?} does not match [{} , {}]",
                self.insert_emission.shape,
                self.global_state_count + 1,
                self.alphabet_size
            )));
        }
        if self.transition_logits.shape != vec![self.global_state_count + 1, TRANSITION_ORDER.len()]
        {
            return Err(PreAdPrepError::Validation(format!(
                "transition_logits shape {:?} does not match [{} , {}]",
                self.transition_logits.shape,
                self.global_state_count + 1,
                TRANSITION_ORDER.len()
            )));
        }
        if self.match_emission.dtype != DataType::F64
            || self.insert_emission.dtype != DataType::F64
            || self.transition_logits.dtype != DataType::F64
        {
            return Err(PreAdPrepError::Validation(
                "initialization arrays must use float64 for compatibility with legacy exports"
                    .into(),
            ));
        }
        Ok(())
    }

    pub fn manifest_path(root: impl AsRef<Path>, track: InitializationTrack) -> PathBuf {
        root.as_ref()
            .join("initialization")
            .join(track.as_manifest_str())
            .join("manifest.json")
    }

    pub fn write_to_path(&self, path: impl AsRef<Path>) -> Result<()> {
        self.validate_shapes()?;
        let path = path.as_ref();
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)?;
        }
        let data = serde_json::to_vec_pretty(self)?;
        fs::write(path, data)?;
        Ok(())
    }

    pub fn read_from_path(path: impl AsRef<Path>) -> Result<Self> {
        let data = fs::read(path)?;
        let manifest: Self = serde_json::from_slice(&data)?;
        manifest.validate_shapes()?;
        Ok(manifest)
    }
}

/// Collection of initialization tracks exported for the same graph.
#[derive(Debug, Clone, Default)]
pub struct InitializationBundle {
    pub tracks: Vec<InitialPhmmManifest>,
}

impl InitializationBundle {
    pub fn add_track(&mut self, manifest: InitialPhmmManifest) {
        self.tracks.retain(|track| track.track != manifest.track);
        self.tracks.push(manifest);
    }

    pub fn get(&self, track: InitializationTrack) -> Option<&InitialPhmmManifest> {
        self.tracks.iter().find(|manifest| manifest.track == track)
    }

    pub fn load_from_root(root: impl AsRef<Path>) -> Result<Self> {
        let root = root.as_ref();
        let mut bundle = Self::default();
        for track in [
            InitializationTrack::LegacyCurrent,
            InitializationTrack::ReferenceMsa,
        ] {
            let path = InitialPhmmManifest::manifest_path(root, track);
            if path.exists() {
                bundle.add_track(InitialPhmmManifest::read_from_path(path)?);
            }
        }
        Ok(bundle)
    }
}

pub fn write_initialization_track(
    root: impl AsRef<Path>,
    track: InitializationTrack,
    global_state_count: usize,
    alphabet_size: usize,
    match_emission: &[f64],
    insert_emission: &[f64],
    transition_logits: &[f64],
    metadata: Vec<(String, String)>,
) -> Result<InitialPhmmManifest> {
    let root = root.as_ref();
    let track_dir = root.join("initialization").join(track.as_manifest_str());
    fs::create_dir_all(&track_dir)?;

    write_npy_2d(
        track_dir.join("match_emission.npy"),
        match_emission,
        global_state_count,
        alphabet_size,
    )?;
    write_npy_2d(
        track_dir.join("insert_emission.npy"),
        insert_emission,
        global_state_count + 1,
        alphabet_size,
    )?;
    write_npy_2d(
        track_dir.join("transition_logits.npy"),
        transition_logits,
        global_state_count + 1,
        TRANSITION_ORDER.len(),
    )?;

    let mut manifest = InitialPhmmManifest::new(
        track,
        global_state_count,
        alphabet_size,
        ArraySpec::new(
            "match_emission",
            format!(
                "initialization/{}/match_emission.npy",
                track.as_manifest_str()
            ),
            DataType::F64,
            vec![global_state_count, alphabet_size],
        ),
        ArraySpec::new(
            "insert_emission",
            format!(
                "initialization/{}/insert_emission.npy",
                track.as_manifest_str()
            ),
            DataType::F64,
            vec![global_state_count + 1, alphabet_size],
        ),
        ArraySpec::new(
            "transition_logits",
            format!(
                "initialization/{}/transition_logits.npy",
                track.as_manifest_str()
            ),
            DataType::F64,
            vec![global_state_count + 1, TRANSITION_ORDER.len()],
        ),
    );
    manifest.metadata = metadata;
    manifest.write_to_path(track_dir.join("manifest.json"))?;
    Ok(manifest)
}
